<?php
/**
 * UnitsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Kaufland
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * The version of the OpenAPI document: 2.18.3
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Kaufland\Test\Api;

use \OpenAPI\Client\Kaufland\Configuration;
use \OpenAPI\Client\Kaufland\ApiException;
use \OpenAPI\Client\Kaufland\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UnitsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Kaufland
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UnitsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bulkUpdateUnits
     *
     * Update some fields of a given set of units.
     *
     */
    public function testBulkUpdateUnits()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createUnit
     *
     * Add a unit.
     *
     */
    public function testCreateUnit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteUnit
     *
     * Delete a unit.
     *
     */
    public function testDeleteUnit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUnit
     *
     * Get a unit by ID.
     *
     */
    public function testGetUnit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUnits
     *
     * Get a list of your units.
     *
     */
    public function testGetUnits()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchUnit
     *
     * Update some of the fields of a unit.
     *
     */
    public function testPatchUnit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
