<?php
/**
 * WarehousesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Kaufland
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * The version of the OpenAPI document: 2.18.3
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Kaufland\Test\Api;

use \OpenAPI\Client\Kaufland\Configuration;
use \OpenAPI\Client\Kaufland\ApiException;
use \OpenAPI\Client\Kaufland\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WarehousesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Kaufland
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WarehousesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createWarehouse
     *
     * Create a new Warehouse.
     *
     */
    public function testCreateWarehouse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWarehouse
     *
     * Delete a warehouse.
     *
     */
    public function testDeleteWarehouse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWarehouse
     *
     * Get a warehouse by its ID.
     *
     */
    public function testGetWarehouse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWarehouses
     *
     * Get a list of your Warehouses.
     *
     */
    public function testGetWarehouses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWarehouse
     *
     * Update a Warehouse.
     *
     */
    public function testUpdateWarehouse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
